GET http://localhost:8082/shutdownJobs
Content-Type: application/json

###
GET http://localhost:8082/startJobs
Content-Type: application/json

###
POST http://localhost:8082/addJob
Content-Type: application/json

{
  "jobName": "testJob",
  "time": "0/10 * * * * ?"
}

###
POST http://localhost:8082/modifyJobTime
Content-Type: application/json

{
  "jobName": "testJob",
  "time": "0 0/1 * * * ?"
}

###
GET http://localhost:8082/removeJob?jobName=testJob
Content-Type: application/json

###
GET http://localhost:8082/getInfo
Content-Type: application/json

###
