GET http://localhost:8082/quartz/getInfo
Content-Type: application/json

###
GET http://localhost:8082/quartz/standbyJobs
Content-Type: application/json

###
GET http://localhost:8082/quartz/startJobs
Content-Type: application/json

###
POST http://localhost:8082/quartz/addJob
Content-Type: application/json

{
  "jobName": "third",
  "jobGroupName": "helloworld",
  "triggerName": "third",
  "triggerGroupName": "helloworld",
  "clsName": "com.takooya.quartz.DynamicJob",
  "time": "0/10 * * * * ?",
  "parameter": {
    "jobName": "printUserJob"
  }
}

###
POST http://localhost:8082/quartz/modifyJob
Content-Type: application/json

{
  "jobName": "first",
  "jobGroupName": "helloworld",
  "triggerName": "first",
  "triggerGroupName": "helloworld",
  "time": "0/20 * * * * ?"
}

###
POST http://localhost:8082/quartz/removeJob
Content-Type: application/json

{
  "jobName": "third",
  "jobGroupName": "helloworld",
  "triggerName": "third",
  "triggerGroupName": "helloworld"
}

###

### 关闭后无法启动
GET http://localhost:8082/quartz/shutdownJobs
Content-Type: application/json

###